namespace Music.Helpers;

// Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
// If you change the class to 'public' in order to use it outside its assembly
//  you should also change the fields from 'const' to 'public static readonly'
public static class IcoMoon
{
    public static readonly string PlayCircle = "\ue902";
    public static readonly string Radio = "\ue903";
    public static readonly string Search = "\ue905";
    public static readonly string Grid = "\ue908";
    public static readonly string Folders = "\ue909";
}
